package mypkg;

/* 2. 
 * Write a Java application which, within the main() method, contains a squence of code that may throw various
 * exceptions, such as ArithmeticException, ArrayIndexOutOfBoundsException, NullPointerException,
 * NumberFormatException, as well as others which you consider to be useful for testing. In the catch block show the
 * corresponding message generated by these exceptions. The finally block just prints the message, "I may or may not have caught an exception".
 */
public class OvidiuGherman_Lab06_P02 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
