package lab9;

import java.util.Random;

/* 2. 
 * Write a Java application with a thread that generates 30 random numbers between 0 and 30. Another thread displays
 * the area of the circles having as radiuses the values divisible by 3 generated by the first thread. 
 */

public class OvidiuGherman_Lab09_P02 {

	public static void main(String[] args) {
		int nrs[] = new int[30];
		
		Thread generatorThread = new Thread(() -> {
			System.out.println("generatorThread started!");
			Random generator = new Random();
			for(int i = 0; i < nrs.length;i++) {
				nrs[i] = generator.nextInt(1,31);
			}
			System.out.println("generatorThread finished generating!");
		});
		Thread computeAreaThread = new Thread(() -> {
			System.out.println("computeAreaThread started!");
			for(int i = 0; i < nrs.length;i++) {
				if(nrs[i] % 3 == 0) {
					System.out.println("The area of the circle with radius " + nrs[i] + " is: " + (Math.PI * Math.pow(nrs[i], 2)));
				}
			}
			System.out.println("computeAreaThread finished computing the areas!");
		});
		
		System.out.println("Threads created!");
		
		
		generatorThread.start();
		try {
			generatorThread.join();
		} catch (InterruptedException e1) {
			e1.printStackTrace();
		}
		computeAreaThread.start();		
		
		try {
			computeAreaThread.join();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		System.out.println("Both threads finished their tasks!");
	}

}
